services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/db:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2.5
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - TZ=${TZ}
    ports:
      - "${WIKI_PORT}:3000"
    volumes:
      - ./data/wiki/config:/config
      - ./data/wiki/uploads:/data/uploads
