services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - wikijs

  wiki:
    image: ghcr.io/requarks/wiki:2.5
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - TZ=${TZ}
    ports:
      - "${WIKI_PORT}:3000"
    networks:
      - wikijs
    volumes:
      - ./data/wiki/config:/config
      - ./data/wiki/uploads:/data/uploads
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - wikijs
 
 
networks:
  wikijs:
    driver: bridge
 
volumes:
  elastic:
