version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: outline
      POSTGRES_DB: outline
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
